const idioma: any = {
  "is required": "es requerido",
  "must be the same": "debe ser igual",
  characters: "caracteres",
  min: "min",
  max: "max",
  "is not a valid value": "no es un valor válido",
  "is not a valid email": "no es un email válido",
  "is not a number": "no es un número",
  "is not a valid text": "no es un texto válido",
  "must be greater than": "debe ser mayor que",
  "must be less than ": "debe ser menor que",
  "must be between ": "debe star entre",
  and: "y",
  or: "o",
  list: "listado de {0}",
  add: "agregar",
  edit: "editar",
  delete: "borrar",
  update: "actualizar",
  view: "ver",
  save: "guardar",
  cancel: "cancelar",
  search: "buscar",
  all: "todos",
  active: "activo",
  inactive: "inactivo",
  user: "usuario",
  admin: "administrador",
  adm: "adminitrador",
  team: "equipo",
  owner: "propietario",
  actions: "acciones",
  "empty data": "no hay datos",
  "are you sure you want to delete the record?":
    "seguro de eliminar el registro?",
  settings: "configuración",
  "sign out": "cerrar sesión",
  wellcome: "bienvenido",
  "password is required": "la contraseña es requerida",
  "email is required": "el email es requerido",
  "welcome to": "bienvenido a",
  "please sign-in to your account and start the adventure":
    "por favor ingrese a su cuenta y comience la aventura",
  "sign in": "ingresar",
  "advanced search": "búsqueda avanzada",
  equal: "igual",
  "not equal": "no igual",
  contains: "contiene",
  "not contains": "no contiene",
  "starts with": "empieza con",
  "ends with": "termina con",
  "greater than": "mayor que",
  "less than": "menor que",
  "greater or equal": "mayor o igual",
  "less or equal": "menor o igual",
  field: "campo",
  value: "valor",
  "search by": "buscar por",
  criteria: "criterio",
};
export default idioma;
